apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "web-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.port | default 8080 }}
      targetPort: {{ $port.targetPort | default "http" }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort | int64 }}
      {{- end }}
      protocol: {{ $port.protocol | default "TCP" }}
      name: {{ $port.name | default "http" }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "web-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
